### ISSUE TITLE
(Question) How to set a batch-size for data to be fetched from DB?

### ISSUE THREAD

**Issue by ff-sdesai** [medzin/beam-postgres#2]
If I have 100k records in my table, will it first fetch all 100k first and then go to next step for each record?
Also, is there a way to configure a batch size for data fetch say 10k?

**Comment by medzin** [comment]
Unfortunately, there is no way to configure reading in batches at the moment (there is only `ReadAllFromPostgres` function that assumes that everything will be returned in one database query). We could add `ReadFromPostgres` function that will read data in batches. It should be pretty straightforward if we assume that we don't need to handle updates/inserts in the meantime.

You can also try to `beam.Reshuffle()` after the database read to redistribute data among all workers.

**Comment by ff-sdesai** [comment]
It won't automatically re-distribute the read records among all workers without `beam.Reshuffle()`? Also, if there are lacs of records in DB table, it will result in query taking too much time?
How much time will it take for you to add the function to read data in batches?

**Comment by medzin** [comment]
I will need one/two weeks to add that feature (I have a lot of other work to do before).

**Comment by ff-sdesai** [comment]
Thanks. One/two weeks should be fine with me. After you add support for batching which of the following two ways it will work?

1. Fetches first batch, distributes it amongst the workers and starts fetching next batch from DB without waiting for workers to complete execution of first batch  OR
2. Fetches first batch, distributes it amongst the workers,waits for workers to finish processing first batch. Once done, starts fetching second batch

**Comment by medzin** [comment]
I will implement it as `BoundedSource` so the runner can decide the bundle size and the reading speed. I can add an extra option to limit batching if the runner will set the value too high for the database to handle.

**Comment by ff-sdesai** [comment]
Yes, that would be nice

**Comment by ff-sdesai** [comment]
@medzin  Just wanted to check did you get a chance to start on this one?

**Comment by ff-sdesai** [comment]
@medzin We have integrated this library as input connector in our Apache beam pipeline. Can you please confirm if you have started on adding support for batched input reading?

**Comment by medzin** [comment]
@ff-sdesai started working on the code here: https://github.com/medzin/beam-postgres/tree/issue/2

**Comment by ff-sdesai** [comment]
Thanks. Appreciate it.

**Comment by ff-sdesai** [comment]
@medzin Can you please update the documentation also to indicate how the batching can be used?

**Comment by medzin** [comment]
PTAL: https://github.com/medzin/beam-postgres#reading-in-batches

**Comment by ff-sdesai** [comment]
Thanks
