### ISSUE TITLE
Is it compatible with Python 3.8 or 3.11?

### ISSUE THREAD

**Issue by geezylucas** [medzin/beam-postgres#4]
I need to use these library in composer (airflow) through but I only use python 3.8 or 3.11.
Any suggestion? 

Thank you.

**Comment by medzin** [comment]
I don't think you should experience any issues with these Python versions.

**Comment by geezylucas** [comment]
Great, I tested it and we can use it in Python 3.8 and 3.11.

https://github.com/medzin/beam-postgres/pull/5

Evidence: 

<img width="1427" alt="image" src="https://github.com/medzin/beam-postgres/assets/51673446/61647f77-9e2d-4817-9407-e91fb0e89c30">

**Comment by medzin** [comment]
Closing as the config is merged now :)
