### ISSUE TITLE
Assistance with reading from a postgres database

### ISSUE THREAD

**Issue by paigewilliams** [medzin/beam-postgres#7]
Hi! I am successfully using this library to write to a postgres database, but am having difficulty reading from the same database. I am using the library in dataflow and would like to use `ReadAllFromPostgres` as a step in my pipeline, taking a PCollection and doing a select along the lines of:
```python
from psycopg.rows import dict_row

data | "check if id is already in the database" >> ReadAllFromPostgres(
          connection_string,
          "SELECT EXISTS (SELECT id FROM sample_table WHERE id = %(id)s);",
          dict_row,
      ) 
```

When I run the following I just get `AssertionError`. I want to make sure that I can reference properties in the elements of my PCollection in my SQL query.  Is there anything obvious I am doing wrong? 

Appreciate any help!

**Comment by medzin** [comment]
The answer is simple - the lib currently does not support parameterized queries in read transforms. It has to be implemented to work :)
